package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_HCRS"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_HCRS")
      userToken : UserToken()
   then
      System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE =  new SearchEntity("SBE_SUMMARY_HCRS", "Host Company Representatives")
								/* Sorts */
								.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
								.addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC)
								.addSort("PRI_ASSOC_HC","Company",SearchEntity.Sort.ASC)

								/* Filters */
								.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
								.addFilter("PRI_IS_HOST_CPY_REP", true)

								/* Columns */
								.addColumn("PRI_NAME", "Name")
								.addColumn("PRI_STATUS", "Status")

								/* Actions */
								.addAction("PRI_EVENT_VIEW", "View")
								.addSearchAction("PRI_EVENT_QUE_HOST_CPY_REP_MENU", "Add")
								.addSearchAction("PRI_EVENT_QUE_TREE_ITEM_HCRS", "View")

								/* Display Mode */
								.setDisplayMode("dashboard_search")
								.setPageStart(0).setPageSize(10);

      searchBE.setRealm(userToken.getRealm());
      CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
