package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_INTERNSHIPS"
    ruleflow-group 'Summary'
     no-loop true
    when
       not  SearchEntity (code == "SBE_SUMMARY_INTERNSHIPS")
       userToken : UserToken()
     then
     	System.out.println("   Generate "+drools.getRule().getName() );

		SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_INTERNSHIPS", "Internships - Active")
			.addSort("PRI_NAME","Title",SearchEntity.Sort.ASC)
			.addFilter("PRI_IS_INTERNSHIP", true)
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "BEG_%")
			.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "ACTIVE")
			.addFilter("PRI_ADDRESS_STATE", SearchEntity.StringFilter.LIKE, "%")
			.addFilter("PRI_ASSOC_INDUSTRY", SearchEntity.StringFilter.LIKE, "%")
			
			/* Table Columns */
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_START_DATE", "Start Date")
			
			/* Actions */
			.addSearchAction("PRI_EVENT_QUE_INTERNSHIP_MENU", "Add")
			.addSearchAction("PRI_EVENT_QUE_TREE_ITEM_INTERNSHIPS", "View")

			/* Display Mode */
			.setDisplayMode("dashboard_search")
			.setPageStart(0)
			.setPageSize(GennySettings.defaultBucketSize());

        searchBE.setRealm(userToken.getRealm());
		CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
