package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_INTERVIEWS"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_INTERVIEWS")
      userToken : UserToken()
   then
     	System.out.println("   Generate "+drools.getRule().getName() );

        SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_INTERVIEWS", "Upcoming Interviews")
                              .addSort("PRI_INTERVIEW_START_DATETIME", "Interview Date Time", SearchEntity.Sort.ASC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "INTERVIEWED")
                              .addFilter("PRI_DISABLED", false)

                              /* Columns */
                              /* .addColumn("PRI_INTERN_NAME", "Name") */
                              .addAssociatedColumn("PRI_INTERN_CODE", "PRI_NAME", "Name")
                              .addColumn("PRI_TITLE", "Internship")
                              .addColumn("PRI_INTERVIEW_START_DATETIME", "Interview Date")
                              .addColumn("PRI_INTERVIEW_TYPE", "Interview Type")
                              
                              /* Actions */
                              .addAction("PRI_EVENT_VIEW_APPLICATION", "View Application")
                              .addAction("PRI_EVENT_VIEW", "View Profile")
                              
                              /* Display Mode */
                              .setDisplayMode("dashboard_search")
                              .setPageStart(0).setPageSize(10);

        searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
