package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_SERVICE_AGREEMENT_DOC"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_SERVICE_AGREEMENT_DOC")
      userToken : UserToken()
   then
      System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_SERVICE_AGREEMENT_DOC", "Host Company Services Agreement")
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "CPY_%")
                     			.addFilter("PRI_IS_HOST_CPY", true)
                              .addColumn("PRI_VALIDATION", "Validation")
                              
                              /* Validation Attribute */
                              .setValidationAttribute("PRI_VALIDATION")
                              
                              /* Actions */
                              .addAction("PRI_EVENT_DOWNLOAD_SERVICE_AGREEMENT_DOC_VALIDATED", "Download")
                              .addAction("PRI_EVENT_HC_SERVICES_AGREEMENT_UNVALIDATED", "Please Complete")
                              
                              /* Display Mode */
                              .setDisplayMode("hero_task")
                              .setPageStart(0).setPageSize(1);

        searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
