package life.genny.gadatron;

import lombok.experimental.UtilityClass;

@UtilityClass
public class Constants {
    public static final String PRODUCT_CODE = "gadatron";
    public static final String SBE_TREE_ITEM_COMPANIES = "SBE_TREE_ITEM_COMPANIES";
    public static final String SBE_TREE_ITEM_PERSONS = "SBE_TREE_ITEM_PERSONS";
    public static final String SBE_TREE_ITEM_DOCUMENTS = "SBE_TREE_ITEM_DOCUMENTS";
    public static final String SBE_TREE_ITEM_MESSAGES = "SBE_TREE_ITEM_MESSAGES";
    public static final String PRI_COMPANY_DESCRIPTION = "PRI_COMPANY_DESCRIPTION";
    public static final String LNK_NUMBER_STAFF = "LNK_NUMBER_STAFF";
    public static final String LNK_COMPANY_INDUSTRY = "LNK_COMPANY_INDUSTRY";
    public static final String PRI_LINKEDIN_URL = "PRI_LINKEDIN_URL";
    public static final String PRI_WEBSITE = "PRI_WEBSITE";
    public static final String PRI_LEGAL_NAME = "PRI_LEGAL_NAME";
    public static final String PRI_ABN = "PRI_ABN";
    public static final String PRI_ADDRESS_COUNTRY = "PRI_ADDRESS_COUNTRY";
    public static final String PRI_ADDRESS_STATE = "PRI_ADDRESS_STATE";
    public static final String PRI_ADDRESS_FULL = "PRI_ADDRESS_FULL";
    public static final String PRI_PHONE = "PRI_PHONE";
    public static final String PRI_HC_VALIDATION_DOC_URL = "PRI_HC_VALIDATION_DOC_URL";
    public static final String PRI_LOGO = "PRI_LOGO";
    public static final String PRI_STATUS = "PRI_STATUS";
    public static final String PRI_CREATED_DATE = "PRI_CREATED_DATE";
    public static final String PRI_CODE = "PRI_CODE";
    public static final String PRI_NAME = "PRI_NAME";
    public static final String PRI_VIDEO_URL = "PRI_VIDEO_URL";
    public static final String PRI_ASSOC_AGENCY = "PRI_ASSOC_AGENCY";
    public static final String PRI_UPDATE_LINKEDIN = "PRI_UPDATE_LINKEDIN";
    public static final String PRI_EDU_PROVIDER_NAME = "PRI_EDU_PROVIDER_NAME";
    public static final String PRI_INDUSTRY = "PRI_INDUSTRY";
    public static final String PRI_AGENT_NAME = "PRI_AGENT_NAME";
    public static final String PRI_MOBILE = "PRI_MOBILE";
    public static final String PRI_EMAIL = "PRI_EMAIL";
    public static final String PRI_ROLES_AND_RESPONSIBILITIES = "PRI_ROLES_AND_RESPONSIBILITIES";
    public static final String PRI_INTRO_VIDEO = "PRI_INTRO_VIDEO";
    public static final String PRI_ADDRESS_SUBURB = "PRI_ADDRESS_SUBURB";
    public static final String PRI_PERCENTAGE_JOURNALS = "PRI_PERCENTAGE_JOURNALS";
    public static final String PRI_OCCUPATION = "PRI_OCCUPATION";
    public static final String PRI_DAYS_PER_WEEK = "PRI_DAYS_PER_WEEK";
    public static final String PRI_INTERN_STUDENT_ID = "PRI_INTERN_STUDENT_ID";
    public static final String PRI_IS_EDU_PROVIDER_ACADEMY = "PRI_IS_EDU_PROVIDER_ACADEMY";
    public static final String PRI_INTERNSHIP_DURATION = "PRI_INTERNSHIP_DURATION";
    public static final String PRI_IS_PROFILE_COMPLETED = "PRI_IS_PROFILE_COMPLETED";
    public static final String PRI_CREATED = "PRI_CREATED";
    public static final String PRI_PROFILE_PICTURE = "PRI_PROFILE_PICTURE";
    public static final String LNK_PERSON = "LNK_PERSON";
    public static final String PRI_NO_OF_INTERNS = "PRI_NO_OF_INTERNS";
    public static final String PRI_WHICH_DAYS_STRIPPED = "PRI_WHICH_DAYS_STRIPPED";
    public static final String PRI_BASE_LEARNING_OUTCOMES = "PRI_BASE_LEARNING_OUTCOMES";
    public static final String PRI_PREFERRED_NAME = "PRI_PREFERRED_NAME";
    public static final String PRI_SPECIALISATION = "PRI_SPECIALISATION";
    public static final String PRI_WORKSITE = "PRI_WORKSITE";
    public static final String PRI_SOFTWARE = "PRI_SOFTWARE";
    public static final String PRI_ASSOC_NO_OF_INTERNS = "PRI_ASSOC_NO_OF_INTERNS";
    public static final String PRI_START_DATE = "PRI_START_DATE";
    public static final String PRI_TITLE = "PRI_TITLE";
    public static final String PRI_COMPANY_LOGO = "PRI_COMPANY_LOGO";
    public static final String PRI_IS_INTERN = "PRI_IS_INTERN";
    public static final String PRI_IS_INTERNSHIP = "PRI_IS_INTERNSHIP";
    public static final String CREATED = "Created";
    public static final String SBE_EMAIL = "SBE_EMAIL";
    public static final String PRI_RECIPIENT_LNK = "PRI_RECIPIENT_LNK";
    public static final String PRI_MILESTONE = "PRI_MILESTONE";
    public static final String LNK_COREBE = "LNK_COREBE";
}
