version: '2.3'

services:
  prd_gadatron:
    image: gennyproject/prd_gadatron:latest
    container_name: prd_gadatron
    hostname: prd_gadatron
    depends_on:
      gadaq:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}
    ports:
      - "${PRD_GADATRON_PORT}:${PRD_GADATRON_INTERNAL_PORT}"
    networks:
      - mainproxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready"]
      interval: 10s
      timeout: 10s
      retries: 30
