package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_TERMS_AND_CONDITIONS"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_TERMS_AND_CONDITIONS")
      userToken : UserToken()
   then
		System.out.println(" Generate "+drools.getRule().getName() );

		SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_TERMS_AND_CONDITIONS", "Terms and Conditions")
							/* Columns */
							.addColumn("PRI_TERMS_ACCEPTED", "Terms and Conditions Accepted")

							/* Validation Attribute */
							.setValidationAttribute("PRI_TERMS_ACCEPTED")

							/* Actions */
							.addAction("PRI_EVENT_TERMS_AND_CONDITIONS_VALIDATED", "View")
							.addAction("PRI_EVENT_TERMS_AND_CONDITIONS_UNVALIDATED", "View")

							/* Display Mode */
							.setDisplayMode("hero_task")
							.setPageStart(0).setPageSize(1);

        searchBE.setRealm(userToken.getRealm());
		CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
