package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_COUNT_SHORTLISTED_INTERNS"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_COUNT_SHORTLISTED_INTERNS")
      userToken : UserToken()
   then
      System.out.println(" Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity("SBE_COUNT_SHORTLISTED_INTERNS", "Shortlisted Students")
							.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
							.addFilter("PRI_IS_INTERN", true)
							.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "SHORTLISTED")

							/* Display Mode */
							.setDisplayMode("edu_pro_summary_count")
							.setPageStart(0).setPageSize(1000000);

      searchBE.setRealm(userToken.getRealm());
      CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
