package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_INTERN"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_INTERN")
      userToken : UserToken()
   then
      System.out.println(" Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_INTERN", "My Profile")
                     			.addFilter("PRI_IS_INTERN", true)
                              
                              /* Columns */
                              .addColumn("PRI_NAME", "Name")
                              .addColumn("PRI_EMAIL", "Email")
                              .addColumn("PRI_MOBILE", "Mobile")
                     		  .addColumn("PRI_LINKEDIN_URL", "LinkedIn")
                     		  .addColumn("PRI_CV", "CV")
                     		  .addColumn("PRI_ADDRESS_FULL", "Address")
                     		  .addColumn("PRI_ASSOC_EP", "Education Provider")
                              .addColumn("PRI_STUDENT_ID", "Student Id")
                              .addColumn("PRI_ASSOC_INDUSTRY", "Industry")
                              .addColumn("PRI_ASSOC_OCCUPATION", "Specialisation")
                              .addColumn("PRI_ASSOC_DURATION", "Duration (Weeks)")
                     		  .addColumn("PRI_IMAGE_URL", " ")

                              /* Actions */
                        	  .addAction("PRI_EVENT_EDIT", "Edit")
                              
                              /* Display Mode */
                              .setDisplayMode("my_profile")
                              .setPageStart(0).setPageSize(1);

        searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
