package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_MY_APPLICATIONS"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_MY_APPLICATIONS")
      userToken : UserToken()
   then
      System.out.println(" Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_MY_APPLICATIONS", "Applications")
                              .addSort("PRI_STATUS", "Created", SearchEntity.Sort.DESC)

                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_STATUS", SearchEntity.StringFilter.LIKE, "%")
                              .addFilter("PRI_DISABLED", false)

                              /* Columns */
                              .addColumn("PRI_TITLE", "Internship")
                              .addColumn("PRI_ASSOC_HC", "Host Company")
                              .addColumn("PRI_STATUS", "Status")

                              /* Actions */
                              .addSearchAction("PRI_EVENT_QUE_TREE_ITEM_APPLICATIONS_APPLIED", "View")
                              
                              /* Display Mode */
                              .setDisplayMode("dashboard_search")
                              .setPageStart(0).setPageSize(5);

        searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
