package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "GENERATE_SUMMARY_CODES"
	ruleflow-group 'Summary'
	no-loop true
	when
		not  SearchEntity (code == "GENERATE_SUMMARY_CODES")
		userToken : UserToken()
	then
		System.out.println("Generate "+drools.getRule().getName() );

		List<String> summaryCodes = new ArrayList<>();

		/* HC REP */
		summaryCodes.add("SBE_SUMMARY_SERVICE_AGREEMENT_DOC");
		summaryCodes.add("SBE_SUMMARY_OHNS_AGREEMENT_DOC");
		summaryCodes.add("SBE_SUMMARY_HOST_CPY");
		summaryCodes.add("SBE_SUMMARY_INTERNSHIPS");
		summaryCodes.add("SBE_SUMMARY_HCRS");
		/* summaryCodes.add("SBE_SUMMARY_INTERVIEWS"); */
		
		/* INTERN */
		summaryCodes.add("SBE_SUMMARY_INTERN");
		summaryCodes.add("SBE_SUMMARY_MY_APPLICATIONS");
		summaryCodes.add("SBE_SUMMARY_INTERVIEWS_INTERN");
		summaryCodes.add("SBE_SUMMARY_INPROGRESS_APPLICATION");
		
		/* EDU PRO REP */
		summaryCodes.add("SBE_COUNTS_EDU_PRO_REP");
		summaryCodes.add("SBE_SUMMARY_EDU_PRO");
		summaryCodes.add("SBE_SUMMARY_EPRS");
		summaryCodes.add("SBE_SUMMARY_INTERNS");
		
		/* AGENT */
		summaryCodes.add("SBE_SUMMARY_AGENCY");
		summaryCodes.add("SBE_SUMMARY_AGENTS");
		summaryCodes.add("SBE_SUMMARY_INTERNS");
		
		summaryCodes.add("SBE_AVAILABLE_INTERNS");
		summaryCodes.add("SBE_APPLIED_APPLICATIONS");
		summaryCodes.add("SBE_SHORTLISTED_APPLICATIONS");
		summaryCodes.add("SBE_INTERVIEWED_APPLICATIONS");
		summaryCodes.add("SBE_OFFERED_APPLICATIONS");
		summaryCodes.add("SBE_PLACED_APPLICATIONS");
		summaryCodes.add("SBE_INPROGRESS_APPLICATIONS");
		

		CacheUtils.putObject(userToken.getRealm(), "SUMMARY_CODES", summaryCodes);
end
