package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_AGENCY"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_AGENCY")
      userToken : UserToken()
   then
      System.out.println(" Generate " + drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_AGENCY", "Complete Agency Profile")
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "CPY_%")
			                  .addFilter("PRI_IS_AGENCY", true)
                              .addColumn("PRI_VALIDATION", "Validation")
                              .addColumn("PRI_NAME", "Name")
                              .addColumn("PRI_EMAIL", "Email")
                              .addColumn("PRI_PHONE", "Phone")
                              .addColumn("PRI_IMAGE_URL", " ")
                              /* Display Mode */
                              .setDisplayMode("my_agency")
                              .setPageStart(0).setPageSize(1);

      searchBE.setRealm(userToken.getRealm());
      CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
