package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_APPOINTMENTS"
	ruleflow-group 'sidebar'
	no-loop true
	when
		not  SearchEntity (code == "SBE_APPOINTMENTS")
		userToken : UserToken()
	then
		System.out.println("   Generate "+drools.getRule().getName() );

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Appointments")
			.addSort("PRI_CREATED", "Created", SearchEntity.Sort.DESC)
			.addFilter("PRI_CODE",SearchEntity.StringFilter.LIKE,"APT_%")
            .addFilter("PRI_IS_APPOINTMENT", true)
			.addColumn("PRI_CODE", "Code")
			.addColumn("PRI_NAME", "Name")
            .addColumn("PRI_DURATION_MIN", "Minimum Duration")
            .addColumn("PRI_START_DATETIME", "Start Date")
            .addColumn("PRI_ACTUAL_START_DATETIME", "Actual Start Date")
            .addColumn("PRI_GENERIC_URL", "URL (Optional)")
            /* .addColumn("LNK_SELECT_TOOL", "Select Tool") */
			.addColumn("LNK_RESOURCES", "Resources")
            .addColumn("LNK_RESOURCES_ACCEPTED", "Accepted Resources")
            .addAction("EDIT", "Edit")
			.setPageStart(0)
			.setPageSize(10000);

		searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
