package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_COMMUNICATIONS"
	ruleflow-group 'sidebar'
	no-loop true
	when
		not  SearchEntity (code == "SBE_COMMUNICATIONS")
		userToken : UserToken()
	then
		System.out.println("   Generate "+drools.getRule().getName() );

		SearchEntity searchBE = new SearchEntity("SBE_COMMUNICATIONS", "Communications Templates")
			.addSort("PRI_NAME", "Name", SearchEntity.Sort.ASC)
            /*.addSort("PRI_CREATED_DATE", "Date Created", SearchEntity.Sort.DESC)*/
			.addFilter("PRI_CODE",SearchEntity.StringFilter.LIKE,"MSG_%")

			.addColumn("PRI_CODE", "Code")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_DESCRIPTION", "Description")
			.addColumn("PRI_DEFAULT_MSG_TYPE", "Default Message Type")
			.addColumn("PRI_CONTEXT_LIST", "Context List")
			.addColumn("PRI_CONTEXT_ASSOCIATIONS", "Context Associations")
			.addColumn("PRI_CC", "CC")
			.addColumn("PRI_BCC", "BCC")
			.addColumn("PRI_BODY", "Body")

		    .addAction("PRI_EVENT_EDIT_MESSAGE", "Edit")

			.setPageStart(0)
			.setPageSize(10000);


	    searchBE.setRealm(userToken.getRealm());
    	CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
