package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;
import life.genny.qwandaq.EEntityStatus;

rule "SBE_DEV_UI"
	ruleflow-group 'sidebar'
	no-loop true
	when
		not  SearchEntity (code == "SBE_DEV_UI")
		userToken : UserToken()
	then
		System.out.println("   Generate "+drools.getRule().getName() );

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Dev UI")
			.addSort("PRI_CODE", "Code", SearchEntity.Sort.ASC)
			.addColumn("PRI_CODE", "Code")
			.addColumn("PRI_NAME", "Name")
			.addAction("EDIT", "Edit")
			.setSearchStatus(EEntityStatus.DELETED)
			.setPageStart(0)
			.setPageSize(50);

		searchBE.setRealm(userToken.getRealm());
		CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
