package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;
import life.genny.qwandaq.attribute.AttributeInteger;

rule "SBE_EDU_PROVIDERS_VIEW"
    ruleflow-group 'sidebar'
     no-loop true
    when
       not  SearchEntity (code == "SBE_EDU_PROVIDERS_VIEW")
       userToken : UserToken()
     then
     	System.out.println("Generate " + drools.getRule().getName());

		SearchEntity searchBE = new SearchEntity("SBE_EDU_PROVIDERS_VIEW", "Education Providers")
			/* Sorts */
			.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
			
			/* Filters */
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "CPY_%")
			.addFilter("PRI_IS_EDU_PROVIDER", true)
			.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "ACTIVE")
			
			/* Table Columns */
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_ADDRESS_FULL","Address")
			.addColumn("PRI_IMAGE_URL", "Logo")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Name")

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")

			/* Table actions */
			.addAction("PRI_EVENT_VIEW", "View Profile")
			.setPageStart(0).setPageSize(GennySettings.defaultBucketSize());

        AttributeInteger priIndex = new AttributeInteger("PRI_INDEX", "PRI_INDEX");
        searchBE.addAttribute(priIndex, 1.0, 1);

		searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
