package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;
import life.genny.qwandaq.attribute.AttributeInteger;

rule "SBE_HOST_COMPANIES_VIEW"
    ruleflow-group 'sidebar'
     no-loop true
    when
       not  SearchEntity (code == "SBE_HOST_COMPANIES_VIEW")
       userToken : UserToken()
     then
     	System.out.println("Generate " + drools.getRule().getName());

		SearchEntity searchBE = new SearchEntity("SBE_HOST_COMPANIES_VIEW", "Host Companies")
			/* Sorts */
			.addSort("PRI_NAME", "Name", SearchEntity.Sort.ASC)
			.addSort("PRI_CREATED_DATE", "Date Created", SearchEntity.Sort.DESC)
			/* .addSort("PRI_ASSOC_INDUSTRY", "Company Industry", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_ADDRESS_STATE", "State", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_VALIDATION", "Validation", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_STATUS", "Status", SearchEntity.Sort.ASC) */
			
			/* Filters */
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "CPY_%")
			.addFilter("PRI_IS_HOST_CPY", true)
			.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "ACTIVE")
			
			/* Table Columns */
			.addColumn("PRI_IMAGE_URL", "Logo")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_CREATED_DATE", "Date Created")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_VALIDATION", "Validation")
			.addColumn("PRI_MOBILE", "Phone")
			.addColumn("PRI_ADDRESS_FULL","Address")
			.addColumn("PRI_ADDRESS_STATE","State")
			.addColumn("PRI_ADDRESS_COUNTRY","Country")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Name")
			.addFilterableColumn("PRI_ASSOC_INDUSTRY", "Company Industry")
			.addFilterableColumn("PRI_ADDRESS_STATE", "State")
			.addFilterableColumn("PRI_VALIDATION", "Validation")
			.addFilterableColumn("PRI_STATUS", "Status")
			.addFilterableColumn("PRI_CREATED_DATE", "Date Created")

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")

			/* Table actions */
			.addAction("PRI_EVENT_VIEW", "View Profile")
			.setPageStart(0).setPageSize(GennySettings.defaultBucketSize());

        AttributeInteger priIndex = new AttributeInteger("PRI_INDEX", "PRI_INDEX");
        searchBE.addAttribute(priIndex, 1.0, 1);

		searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end

rule "SBE_HOST_COMPANIES"
    ruleflow-group 'sidebar'
     no-loop true
    when
       not  SearchEntity (code == "SBE_HOST_COMPANIES")
       userToken : UserToken()
     then
     	System.out.println("Generate " + drools.getRule().getName());

		SearchEntity searchBE = new SearchEntity("SBE_HOST_COMPANIES", "Host Companies")
			/* Sorts */
			.addSort("PRI_NAME", "Name", SearchEntity.Sort.ASC)
			.addSort("PRI_CREATED_DATE", "Date Created", SearchEntity.Sort.DESC)
			/* .addSort("PRI_ASSOC_INDUSTRY", "Company Industry", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_ADDRESS_STATE", "State", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_VALIDATION", "Validation", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_STATUS", "Status", SearchEntity.Sort.ASC) */

			/* Filters */
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "CPY_%")
			.addFilter("PRI_IS_HOST_CPY", true)
			.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "ACTIVE")

			/* Table Columns */
			.addColumn("PRI_IMAGE_URL", "Logo")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_CREATED_DATE", "Date Created")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_VALIDATION", "Validation")
			.addColumn("PRI_MOBILE", "Phone")
			.addColumn("PRI_ADDRESS_FULL","Address")
			.addColumn("PRI_ADDRESS_STATE","State")
			.addColumn("PRI_ADDRESS_COUNTRY","Country")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Name")
			.addFilterableColumn("PRI_ASSOC_INDUSTRY", "Company Industry")
			.addFilterableColumn("PRI_ADDRESS_STATE", "State")
			.addFilterableColumn("PRI_VALIDATION", "Validation")
			.addFilterableColumn("PRI_STATUS", "Status")
			.addFilterableColumn("PRI_CREATED_DATE", "Date Created")

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")

			/* Table actions */
			.addAction("PRI_EVENT_VIEW", "View Profile")
			.setPageStart(0).setPageSize(GennySettings.defaultBucketSize());

        AttributeInteger priIndex = new AttributeInteger("PRI_INDEX", "PRI_INDEX");
        searchBE.addAttribute(priIndex, 1.0, 1);

		searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end