package life.genny.gadaq.bucket;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.BaseEntity;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.qwandaq.models.GennySettings;

rule "inprogressApp"
    ruleflow-group 'bucket'
     no-loop true
    when
       not  SearchEntity (code == "SBE_INPROGRESS_APPLICATIONS")
        userToken : UserToken()
     then
     	System.out.println("   Generate "+drools.getRule().getName() );

        SearchEntity searchBE = new SearchEntity("SBE_INPROGRESS_APPLICATIONS", "In Progress")
                              .addSort("PRI_CREATED", "Created", SearchEntity.Sort.DESC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_STAGE", SearchEntity.StringFilter.EQUAL, "PROGRESS")
                              .addFilter("PRI_DISABLED", false)

                              .addAssociatedColumn("PRI_INTERN_CODE", "PRI_NAME", "Name")
                              .addAssociatedColumn("LNK_INTERNSHIP", "LNK_HOST_COMPANY", "PRI_NAME", "Host Company")
                              .addAssociatedColumn("LNK_INTERNSHIP", "PRI_NAME", "Internship")
                              .addAssociatedColumn("LNK_EDU_PROVIDER", "PRI_NAME", "Education Provider")
                              /* .addColumn("PRI_ASSOC_HC", "Host Company") */
                              /* .addColumn("PRI_TITLE", "Internship") */
                              .addColumn("PRI_END_DATE", "End Date")
                              .addColumn("PRI_PROGRESS", "Application Progress")

                              .addColumn("PRI_INTERN_STUDENT_ID", "Student ID")
                              .addColumn("PRI_ASSOC_INDUSTRY", "Industry")
                              .addColumn("PRI_ASSOC_EP", "Edu Provider")
                              .addColumn("PRI_ASSOC_OCCUPATION", "Occupation")
                              .addColumn("PRI_ADDRESS_FULL", "Address")
                              .addColumn("PRI_TRANSPORT", "Transport")
                              .addColumn("PRI_INTERN_MOBILE", "Mobile")
                              .addColumn("PRI_INTERN_EMAIL", "Email")

                              .addColumn("PRI_STATUS_COLOR", " ")
                              .addColumn("PRI_IMAGE_URL", " ")
                              .addColumn("PRI_IMAGE_SECONDARY", " ")
							  .addAssociatedColumn("PRI_INTERN_CODE", "LNK_AGENT", "PRI_NAME", "Agent Name")
							  .addAssociatedColumn("PRI_INTERN_CODE", "LNK_AGENT", "PRI_IMAGE_URL", "Agent Image")
							  .addAssociatedColumn("LNK_COMP_INTERNSHIP", "PRI_COLOUR", "Completing Internship Type Colour")

                              .addColumn("PRI_START_DATE", "Internship Start Date")
                              .addColumn("PRI_END_DATE", "Internship End Date")
                              .addColumn("PRI_ASSOC_DURATION", "Internship Duration")
                              .addColumn("PRI_DAYS_PER_WEEK", "Number of Days per week")

							  /* Wildcard blacklist */
							  /* .addBlacklist("PRI_ROLES_AND_RESPONSIBILITIES") */
							  /* .addBlacklist("PRI_BASE_LEARNING_OUTCOMES") */

							  /* Wildcard Whitelisted Attributes */
							  .addWhitelist("PRI_NAME")

                              .setDisplayMode("CARD:MAIN_5")
                               /* Actions */
                              .addAction("PRI_EVENT_ACCESS_NOTES_APPLICATION", "Access Notes")
							  .addAction("PRI_EVENT_VIEW_APPLICATION", "View Internship Summary")
							  .addAction("PRI_EVENT_VIEW_AGREEMENT", "View/Sign Agreement Document")
							  .addAction("PRI_EVENT_VIEW", "View Intern Profile")
							  .addAction("PRI_EVENT_JOURNAL_VIEW", "View Logbook")
							  .addAction("PRI_EVENT_FINISH_APPLICATION", "Finish Internship")
							  .addAction("PRI_EVENT_EDIT_AGREEMENT", "Edit Agreement Document Data")
							  .addAction("PRI_EVENT_DOWNLOAD_INTERNSHIP_AGREEMENT_DOC", "Download Internship Agreement Document")
							  .addAction("PRI_EVENT_ON_HOLD_APPLICATION", "On Hold")
							  .addAction("PRI_EVENT_WITHDRAW_APPLICATION", "Withdraw")
							  .setCachable(true)
							  .setWildcardDepth(2)
                              .setPageStart(0)
                              .setPageSize(GennySettings.defaultBucketSize());

        searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);
end
