package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_EPRS"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_EPRS")
      userToken : UserToken()
   then
      System.out.println(" Generate "+drools.getRule().getName() );

      SearchEntity searchBE =  new SearchEntity("SBE_SUMMARY_EPRS", "Education Provider Representatives")
                              .addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
                              .addFilter("PRI_IS_EDU_PRO_REP", true)

                              /* Columns */
                              .addColumn("PRI_STATUS", "Status")
                              .addColumn("PRI_NAME", "Name")
                              .addColumn("PRI_EMAIL", "Email")
                              .addColumn("PRI_MOBILE", "Mobile")
                              .addColumn("PRI_JOB_TITLE", "Job Title")
                     		  .addColumn("PRI_IMAGE_URL", " ")
                              
                              /* Actions */
                     		  .addAction("PRI_EVENT_VIEW", "View")
                              .addSearchAction("PRI_EVENT_QUE_EDU_PRO_REP_MENU", "Add")
                     		  .addSearchAction("PRI_EVENT_QUE_TREE_ITEM_EPRS", "View")
                              
                              /* Display Mode */
                              .setDisplayMode("edu_pro_reps")
                              .setPageStart(0).setPageSize(10);

      searchBE.setRealm(userToken.getRealm());
      CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
