package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;

rule "SBE_SUMMARY_EDU_PRO"
   ruleflow-group 'Summary'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_EDU_PRO")
      userToken : UserToken()
   then
      System.out.println(" Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity("SBE_SUMMARY_EDU_PRO", "Education Procvider Details")
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "CPY_%")
                     		  .addFilter("PRI_IS_EDU_PROVIDER", true)
                     		  .addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "ACTIVE")
                              
                              /* Columns */
                     		  .addColumn("PRI_NAME", "Name")
			                  .addColumn("PRI_STATUS", "Status")
                     	      .addColumn("PRI_IMAGE_URL", " ")
                              
                              /* Display Mode */
                              .setDisplayMode("my_education_provider")
                              .setPageStart(0).setPageSize(1);

      searchBE.setRealm(userToken.getRealm());
      CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end
