package life.genny.rules;

import java.util.List;
import java.util.ArrayList;
import life.genny.qwandaq.entity.SearchEntity;
import life.genny.qwandaq.utils.CacheUtils;
import life.genny.qwandaq.models.GennySettings;
import life.genny.qwandaq.models.UserToken;
import life.genny.qwandaq.message.QEventMessage;
import life.genny.qwandaq.attribute.AttributeInteger;

rule "SBE_TABLE_EPRS"
    ruleflow-group 'sidebar'
     no-loop true
    when
       not  SearchEntity (code == "SBE_TABLE_EPRS")
       userToken : UserToken()
     then
     	System.out.println("Generate " + drools.getRule().getName());

		SearchEntity searchBE = new SearchEntity("SBE_TABLE_EPRS", "Education Provider Representatives")
			/* Sorts */
			.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
			/* .addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_ASSOC_EP","Education Provider",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_JOB_TITLE","Job Title",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_DEPARTMENT","Department",SearchEntity.Sort.ASC) */

			/* Filters */
			/* .addFilter("PRI_NAME",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_STATUS",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_ASSOC_EP",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_JOB_TITLE",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_DEPARTMENT",SearchEntity.StringFilter.LIKE, "%%") */
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
			.addFilter("PRI_IS_EDU_PRO_REP", true)

			/* Table Columns */
			.addColumn("PRI_IMAGE_URL", "Profile Picture")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_ASSOC_EP", "Education Provider")
			.addColumn("PRI_EMAIL", "Email")
			.addColumn("PRI_MOBILE", "Mobile")
			.addColumn("PRI_JOB_TITLE", "Job Title")
			.addColumn("PRI_DEPARTMENT", "Department")
			.addColumn("PRI_LINKEDIN_URL", "LinkedIn")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Name")
			.addFilterableColumn("PRI_STATUS", "Status")
			.addFilterableColumn("PRI_ASSOC_EP", "Education Provider")

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")

			/* Table actions */
			.addAction("PRI_EVENT_VIEW", "View Profile")
			.setPageStart(0).setPageSize(GennySettings.defaultBucketSize());

        AttributeInteger priIndex = new AttributeInteger("PRI_INDEX", "PRI_INDEX");
        searchBE.addAttribute(priIndex, 1.0, 1);

		searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end


rule "SBE_EPRS"
    ruleflow-group 'sidebar'
     no-loop true
    when
       not  SearchEntity (code == "SBE_EPRS")
       userToken : UserToken()
     then
     	System.out.println("Generate " + drools.getRule().getName());

		SearchEntity searchBE = new SearchEntity("SBE_EPRS", "Education Provider Representatives")
			/* Sorts */
			.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
			/* .addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_ASSOC_EP","Education Provider",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_JOB_TITLE","Job Title",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_DEPARTMENT","Department",SearchEntity.Sort.ASC) */

			/* Filters */
			/* .addFilter("PRI_NAME",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_STATUS",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_ASSOC_EP",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_JOB_TITLE",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_DEPARTMENT",SearchEntity.StringFilter.LIKE, "%%") */
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
			.addFilter("PRI_IS_EDU_PRO_REP", true)

			/* Table Columns */
			.addColumn("PRI_IMAGE_URL", "Profile Picture")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_ASSOC_EP", "Education Provider")
			.addColumn("PRI_EMAIL", "Email")
			.addColumn("PRI_MOBILE", "Mobile")
			.addColumn("PRI_JOB_TITLE", "Job Title")
			.addColumn("PRI_DEPARTMENT", "Department")
			.addColumn("PRI_LINKEDIN_URL", "LinkedIn")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Name")
			.addFilterableColumn("PRI_STATUS", "Status")
			.addFilterableColumn("PRI_ASSOC_EP", "Education Provider")

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")

			/* Table actions */
			.addAction("PRI_EVENT_VIEW", "View Profile")
			.setPageStart(0).setPageSize(GennySettings.defaultBucketSize());

        AttributeInteger priIndex = new AttributeInteger("PRI_INDEX", "PRI_INDEX");
        searchBE.addAttribute(priIndex, 1.0, 1);

		searchBE.setRealm(userToken.getRealm());
        CacheUtils.putObject(userToken.getRealm(), searchBE.getCode(), searchBE);

end

